//
// ASCII codes for symbols needed for lexing.
//
const int $tab = 0x09; //            '\t'
const int $lineFeed = 0x0A; //       '\n'
const int $carriageReturn = 0x0D; // '\r'
const int $space = 0x20; //          ' '
const int $exclamation = 0x21; //    '!'
const int $doubleQuote = 0x22; //    '"'
const int $hash = 0x23; //           '#'
const int $dollar = 0x24; //         '$'
const int $percent = 0x25; //        '%'
const int $ampersand = 0x26; //      '&'
const int $singleQuote = 0x27; //    '\''
const int $leftParen = 0x28; //      '('
const int $rightParen = 0x29; //     ')'
const int $asterisk = 0x2a; //       '*'
const int $plus = 0x2b; //           '+'
const int $comma = 0x2c; //          ','
const int $minus = 0x2d; //          '-'
const int $dot = 0x2e; //            '.'
const int $slash = 0x2f; //          '/'
const int $digit0 = 0x30; //         '0'
const int $digit9 = 0x39; //         '9'
const int $colon = 0x3a; //          ':'
const int $lessThan = 0x3c; //       '<'
const int $equals = 0x3d; //         '='
const int $greaterThan = 0x3e; //    '>'
const int $uppercaseA = 0x41; //     'A'
const int $uppercaseZ = 0x5a; //     'Z'
const int $leftBracket = 0x5b; //    '['
const int $backslash = 0x5c; //      '\\'
const int $rightBracket = 0x5d; //   ']'
const int $caret = 0x5e; //          '^'
const int $underscore = 0x5f; //     '_'
const int $lowercaseA = 0x61; //     'a'
const int $lowercaseN = 0x6e; //     'n'
const int $lowercaseZ = 0x7a; //     'z'
const int $leftBrace = 0x7b; //      '{'
const int $pipe = 0x7c; //           '|'
const int $rightBrace = 0x7d; //     '}'
