name: flame_texturepacker_example
resolution: workspace
description: An example of how to use the flame_texturepacker package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flame: ^2.0.0-dev.0
  flame_texturepacker: ^5.2.0-dev.0
  flutter:
    sdk: flutter

  material_ui: ^1.0.0
dev_dependencies:
  flame_lint: ^1.4.4-dev.0

flutter:
  assets:
    - assets/images/