name: flame_typled_example
resolution: workspace
description: "An example for the TypledSpriteAtlas."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  flame: ^2.0.0-dev.0
  flame_typled: ^0.2.0-dev.0
  flutter:
    sdk: flutter

  material_ui: ^1.0.0
dev_dependencies:
  flame_lint: ^1.4.4-dev.0

flutter:
  uses-material-design: false
  assets:
    - assets/images/
    - assets/
