name: flame_typled
resolution: workspace
description: Typled sprite atlas support for the Flame Engine
version: 0.1.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_typled
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - typled
  - sprite-atlas

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flame: ^1.37.0
  flutter:
    sdk: flutter
  typled: ^0.0.5

dev_dependencies:
  dartdoc: ^9.0.0
  flame_lint: ^1.4.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: any
