name: flame_rive_example
resolution: workspace
description: A testbed for flame_rive
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flame: ^2.0.0-dev.0
  flame_rive: ^2.0.0-dev.0
  flutter:
    sdk: flutter
  material_ui: ^1.0.0
  rive: ^0.14.0

dev_dependencies:
  flame_lint: ^1.4.4-dev.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
