
var wimp = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

function c(){g.buffer!=k.buffer&&p();return k}function q(){g.buffer!=k.buffer&&p();return aa}function r(){g.buffer!=k.buffer&&p();return ba}function t(){g.buffer!=k.buffer&&p();return ca}function v(){g.buffer!=k.buffer&&p();return da}var w=moduleArg,ea,fa,ha=new Promise((a,b)=>{ea=a;fa=b}),ia="object"==typeof window,ja="function"==typeof importScripts,ka=w.$ww,la=Object.assign({},w),x="";function ma(a){return w.locateFile?w.locateFile(a,x):x+a}var na,oa;
if(ia||ja)ja?x=self.location.href:"undefined"!=typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptName&&(x=_scriptName),x.startsWith("blob:")?x="":x=x.substr(0,x.replace(/[?#].*/,"").lastIndexOf("/")+1),ja&&(oa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));
var pa=console.log.bind(console),y=console.error.bind(console);Object.assign(w,la);la=null;var g,qa,ra=!1,sa,k,aa,ta,ua,ba,ca,da;function p(){var a=g.buffer;k=new Int8Array(a);ta=new Int16Array(a);aa=new Uint8Array(a);ua=new Uint16Array(a);ba=new Int32Array(a);ca=new Uint32Array(a);da=new Float32Array(a);new Float64Array(a)}w.wasmMemory?g=w.wasmMemory:g=new WebAssembly.Memory({initial:256,maximum:32768,shared:!0});p();var va=[],wa=[],xa=[];
function ya(){ka?(za=1,Aa(w.sb,w.sz),removeEventListener("message",Ba),Ca=Ca.forEach(Da),addEventListener("message",Da)):Ea(wa)}var z=0,Fa=null,Ga=null;function Ha(a){a="Aborted("+a+")";y(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");fa(a);throw a;}var Ia=a=>a.startsWith("data:application/octet-stream;base64,"),Ja;
function Ka(a){return na(a).then(b=>new Uint8Array(b),()=>{if(oa)var b=oa(a);else throw"both async and sync fetching of the wasm failed";return b})}function La(a,b,d){return Ka(a).then(e=>WebAssembly.instantiate(e,b)).then(d,e=>{y(`failed to asynchronously prepare wasm: ${e}`);Ha(e)})}
function Ma(a,b){var d=Ja;return"function"!=typeof WebAssembly.instantiateStreaming||Ia(d)||"function"!=typeof fetch?La(d,a,b):fetch(d,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(f){y(`wasm streaming compile failed: ${f}`);y("falling back to ArrayBuffer instantiation");return La(d,a,b)}))}function Na(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ca=[],Oa=a=>{if(!(a instanceof Na||"unwind"==a))throw a;},Pa=0,Qa=a=>{sa=a;za||0<Pa||(ra=!0);throw new Na(a);},Ra=a=>{if(!ra)try{if(a(),!(za||0<Pa))try{sa=a=sa,Qa(a)}catch(b){Oa(b)}}catch(b){Oa(b)}},A,Da=a=>{let b=a.data,d=b._wsc;d&&Ra(()=>A.get(d)(...b.x))},Ba=a=>{Ca.push(a)},Ea=a=>{a.forEach(b=>b(w))},za=w.noExitRuntime||!0;class Sa{constructor(a){this.s=a-24}}
var Ta=0,Ua=0,Va="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Wa=(a,b=0,d=NaN)=>{var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.buffer&&Va)return Va.decode(a.slice(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|l:(f&7)<<18|h<<12|l<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e},
B=(a,b)=>a?Wa(q(),a,b):"",C={},Xa=1,Ya={},D=(a,b,d)=>{var e=q();if(0<d){var f=b;d=b+d-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var m=a.charCodeAt(++h);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(b>=d)break;e[b++]=l}else{if(2047>=l){if(b+1>=d)break;e[b++]=192|l>>6}else{if(65535>=l){if(b+2>=d)break;e[b++]=224|l>>12}else{if(b+3>=d)break;e[b++]=240|l>>18;e[b++]=128|l>>12&63}e[b++]=128|l>>6&63}e[b++]=128|l&63}}e[b]=0;a=b-f}else a=0;return a},E,Za=a=>{var b=a.getExtension("ANGLE_instanced_arrays");
b&&(a.vertexAttribDivisor=(d,e)=>b.vertexAttribDivisorANGLE(d,e),a.drawArraysInstanced=(d,e,f,h)=>b.drawArraysInstancedANGLE(d,e,f,h),a.drawElementsInstanced=(d,e,f,h,l)=>b.drawElementsInstancedANGLE(d,e,f,h,l))},$a=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=d=>b.deleteVertexArrayOES(d),a.bindVertexArray=d=>b.bindVertexArrayOES(d),a.isVertexArray=d=>b.isVertexArrayOES(d))},ab=a=>{var b=a.getExtension("WEBGL_draw_buffers");
b&&(a.drawBuffers=(d,e)=>b.drawBuffersWEBGL(d,e))},bb=a=>{a.ba=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},cb=a=>{a.ca=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},db=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(d=>b.includes(d))},eb=1,F=[],G=[],fb=[],H=[],I=[],J=[],gb=[],K=[],L=[],hb=[],ib={},jb={},kb=4,lb=0,M=a=>{for(var b=eb++,d=a.length;d<b;d++)a[d]=null;return b},mb=(a,b,d,e)=>{for(var f=0;f<a;f++){var h=E[d](),l=h&&M(e);h?(h.name=l,e[l]=h):N||=1282;r()[b+4*f>>2]=l}},ob=(a,b)=>{a.s||(a.s=a.getContext,a.getContext=function(e,f){f=a.s(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var d=1<b.J?a.getContext("webgl2",b):a.getContext("webgl",
b);return d?nb(d,b):0},nb=(a,b)=>{var d=M(K),e={handle:d,attributes:b,version:b.J,m:a};a.canvas&&(a.canvas.M=e);K[d]=e;("undefined"==typeof b.H||b.H)&&pb(e);return d},pb=a=>{a||=O;if(!a.S){a.S=!0;var b=a.m;b.U=b.getExtension("WEBGL_multi_draw");b.P=b.getExtension("EXT_polygon_offset_clamp");b.O=b.getExtension("EXT_clip_control");b.Z=b.getExtension("WEBGL_polygon_mode");Za(b);$a(b);ab(b);bb(b);cb(b);2<=a.version&&(b.o=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.o)b.o=b.getExtension("EXT_disjoint_timer_query");
db(b).forEach(d=>{d.includes("lose_context")||d.includes("debug")||b.getExtension(d)})}},N,O,qb=(a,b)=>{E.bindFramebuffer(a,fb[b])},rb=a=>E.clear(a),sb=(a,b,d,e)=>E.clearColor(a,b,d,e),tb=a=>E.clearStencil(a),ub=(a,b)=>{t()[a>>2]=b;var d=t()[a>>2];t()[a+4>>2]=(b-d)/4294967296};function vb(){var a=db(E);return a=a.concat(a.map(b=>"GL_"+b))}
var wb=(a,b,d)=>{if(b){var e=void 0;switch(a){case 36346:e=1;break;case 36344:0!=d&&1!=d&&(N||=1280);return;case 34814:case 36345:e=0;break;case 34466:var f=E.getParameter(34467);e=f?f.length:0;break;case 33309:if(2>O.version){N||=1282;return}e=vb().length;break;case 33307:case 33308:if(2>O.version){N||=1280;return}e=33307==a?3:0}if(void 0===e)switch(f=E.getParameter(a),typeof f){case "number":e=f;break;case "boolean":e=f?1:0;break;case "string":N||=1280;return;case "object":if(null===f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:e=
0;break;default:N||=1280;return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(d){case 0:r()[b+4*a>>2]=f[a];break;case 2:v()[b+4*a>>2]=f[a];break;case 4:c()[b+a]=f[a]?1:0}return}try{e=f.name|0}catch(h){N||=1280;y(`GL_INVALID_ENUM in glGet${d}v: Unknown object returned from WebGL getParameter(${a})! (error: ${h})`);return}}break;default:N||=1280;y(`GL_INVALID_ENUM in glGet${d}v: Native code calling glGet${d}v(${a}) and it returns ${f} of type ${typeof f}!`);
return}switch(d){case 1:ub(b,e);break;case 0:r()[b>>2]=e;break;case 2:v()[b>>2]=e;break;case 4:c()[b]=e?1:0}}else N||=1281},xb=(a,b)=>wb(a,b,0),yb=a=>{a-=5120;0==a?a=c():1==a?a=q():2==a?(g.buffer!=k.buffer&&p(),a=ta):4==a?a=r():6==a?a=v():5==a||28922==a||28520==a||30779==a||30782==a?a=t():(g.buffer!=k.buffer&&p(),a=ua);return a},zb=(a,b,d,e,f)=>{a=yb(a);b=e*((lb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+kb-1&-kb);return a.subarray(f>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
f+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Ab=(a,b,d,e,f,h,l)=>{if(2<=O.version)if(E.D)E.readPixels(a,b,d,e,f,h,l);else{var m=yb(h);l>>>=31-Math.clz32(m.BYTES_PER_ELEMENT);E.readPixels(a,b,d,e,f,h,m,l)}else(m=zb(h,f,d,e,l))?E.readPixels(a,b,d,e,f,h,m):N||=1280},Bb=()=>{Ha("Cannot use convertFrameToPC (needed by __builtin_return_address) without -sUSE_OFFSET_CONVERTER");return 0},P={},Cb=a=>{a.forEach(b=>{var d=Bb();d&&(P[d]=b)})},Db={},Fb=()=>{if(!Eb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",
PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in Db)void 0===Db[b]?delete a[b]:a[b]=Db[b];var d=[];for(b in a)d.push(`${b}=${a[b]}`);Eb=d}return Eb},Eb,Gb=[null,[],[]],Ib=a=>{for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++d):b+=3}b+=1;(d=Hb(b))&&D(a,d,b);return d},Jb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Kb=[],Q=a=>{var b=
E.N;if(b){var d=b.u[a];"number"==typeof d&&(b.u[a]=d=E.getUniformLocation(b,b.K[a]+(0<d?`[${d}]`:"")));return d}N||=1282},R=[];function Lb(){}function Mb(){}function Nb(){}function Ob(){}function Pb(){}function Qb(){}function Rb(){}function Sb(){}function Tb(){}function Ub(){}function Vb(){}function Wb(){}function Xb(){}function Yb(){}function Zb(){}function $b(){}function ac(){}function bc(){}function cc(){}function dc(){}function ec(){}function fc(){}function gc(){}function T(){}
function hc(){}function ic(){}var U,jc=[],lc=a=>kc(a);w.stackAlloc=lc;ka&&(C[0]=this,addEventListener("message",Ba));for(var V=0;32>V;++V)Kb.push(Array(V));var mc=new Float32Array(288);for(V=0;288>=V;++V)R[V]=mc.subarray(0,V);
(function(){if(w.skwasmSingleThreaded){$b=function(){return!0};let e;Mb=function(f,h){e=h};Nb=function(){return performance.now()};T=function(f){queueMicrotask(()=>e(f))}}else{$b=function(){return!1};let e=0;Mb=function(f,h){function l({data:m}){const n=m.l;n&&("syncTimeOrigin"==n?e=performance.timeOrigin-m.timeOrigin:h(m))}f?(C[f].addEventListener("message",l),C[f].postMessage({l:"syncTimeOrigin",timeOrigin:performance.timeOrigin})):addEventListener("message",l)};Nb=function(){return performance.now()+
e};T=function(f,h,l){l?C[l].postMessage(f,{transfer:h}):postMessage(f,{transfer:h})}}const a=new Map,b=new Map,d=new Map;Ob=function(e){Mb(e,function(f){var h=f.l;if(h)switch(h){case "transferCanvas":nc(f.g,f.canvas,f.h);break;case "onInitialized":oc(f.g,f.h);break;case "resizeSurface":pc(f.g,f.width,f.height,f.h);break;case "onResizeComplete":qc(f.g,f.h);break;case "triggerContextLoss":rc(f.g,f.h);break;case "onContextLossTriggered":sc(f.g,f.h);break;case "reportContextLost":tc(f.g,f.h);break;case "renderPictures":uc(f.g,
f.W,f.V,f.h,Nb());break;case "onRenderComplete":vc(f.g,f.h,{imageBitmaps:f.R,rasterStartMilliseconds:f.Y,rasterEndMilliseconds:f.X});break;case "setAssociatedObject":d.set(f.F,f.object);break;case "disposeAssociatedObject":f=f.F;h=d.get(f);h.close&&h.close();d.delete(f);break;case "disposeSurface":wc(f.g);break;case "rasterizeImage":xc(f.g,f.image,f.format,f.h);break;case "onRasterizeComplete":yc(f.g,f.data,f.h);break;default:console.warn(`unrecognized skwasm message: ${h}`)}})};hc=function(e,f,h){T({l:"setAssociatedObject",
F:f,object:h},[h],e)};Yb=function(e){return d.get(e)};Xb=function(e,f){T({l:"disposeAssociatedObject",F:f},[],e)};Rb=function(e,f){T({l:"disposeSurface",g:f},[],e)};Vb=function(e,f,h,l){T({l:"transferCanvas",g:f,canvas:h,h:l},[h],e)};dc=function(e,f,h){T({l:"onInitialized",g:e,$:f,h},[])};Ub=function(e,f,h,l,m){T({l:"resizeSurface",g:f,width:h,height:l,h:m},[],e)};ec=function(e,f){T({l:"onResizeComplete",g:e,h:f},[])};fc=function(e,f,h){e=b.get(e);e.width=f;e.height=h};Tb=function(e,f,h,l,m){T({l:"renderPictures",
g:f,W:h,V:l,h:m},[],e)};gc=async function(e,f,h,l){f||=[];T({l:"onRenderComplete",g:e,h:l,R:f,Y:h,X:Nb()},[...f])};Lb=function(e,f){f||=[];e=b.get(e);f.push(e.transferToImageBitmap());return f};Sb=function(e,f,h,l,m){T({l:"rasterizeImage",g:f,image:h,format:l,h:m},[],e)};ac=function(e,f,h){T({l:"onRasterizeComplete",g:e,data:f,h})};Wb=function(e,f,h){T({l:"triggerContextLoss",g:f,h},[],e)};bc=function(e,f){T({l:"onContextLossTriggered",g:e,h:f},[])};cc=function(e,f){T({l:"reportContextLost",g:e,h:f},
[])};ic=function(){O.m.getExtension("WEBGL_lose_context").loseContext()};Zb=function(e,f,h){f=ob(e,{J:2,alpha:!0,depth:!0,stencil:!0,antialias:f,premultipliedAlpha:!0,preserveDrawingBuffer:!1,powerPreference:"default",failIfMajorPerformanceCaveat:!1,H:!0});b.set(f,e);var l=function(m){m.preventDefault();zc(h);e.removeEventListener("webglcontextlost",l)};e.addEventListener("webglcontextlost",l);a.set(f,l);return f};Qb=function(e){const f=b.get(e),h=a.get(e);f&&h&&f.removeEventListener("webglcontextlost",
h);O===K[e]&&(O=null);"object"==typeof JSEvents&&JSEvents.da(K[e].m.canvas);K[e]&&K[e].m.canvas&&(K[e].m.canvas.M=void 0);K[e]=null;b.delete(e);a.delete(e)};Pb=function(e,f,h){const l=O.m,m=l.createTexture();l.bindTexture(l.TEXTURE_2D,m);l.pixelStorei(l.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!0);l.texImage2D(l.TEXTURE_2D,0,l.RGBA,f,h,0,l.RGBA,l.UNSIGNED_BYTE,e);l.pixelStorei(l.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);l.bindTexture(l.TEXTURE_2D,null);e=M(I);I[e]=m;return e}})();
var Jc={__cxa_throw:(a,b,d)=>{var e=new Sa(a);t()[e.s+16>>2]=0;t()[e.s+4>>2]=b;t()[e.s+8>>2]=d;Ta=a;Ua++;throw Ta;},__syscall_fcntl64:function(){return 0},__syscall_fstat64:()=>{},__syscall_ioctl:function(){return 0},__syscall_openat:function(){},_abort_js:()=>{Ha("")},_emscripten_create_wasm_worker:(a,b)=>{let d=C[Xa]=new Worker(ma("wimp.ww.js"));d.postMessage({$ww:Xa,wasm:qa,js:w.mainScriptUrlOrBlob||_scriptName,wasmMemory:g,sb:a,sz:b});d.onmessage=Da;return Xa++},_emscripten_get_now_is_monotonic:()=>
1,_emscripten_runtime_keepalive_clear:()=>{za=!1;Pa=0},_emscripten_throw_longjmp:()=>{throw Infinity;},_mmap_js:function(){return-52},_munmap_js:function(){},_setitimer_js:(a,b)=>{Ya[a]&&(clearTimeout(Ya[a].id),delete Ya[a]);if(!b)return 0;var d=setTimeout(()=>{delete Ya[a];Ra(()=>Ac(a,performance.now()))},b);Ya[a]={id:d,ea:b};return 0},_tzset_js:(a,b,d,e)=>{var f=(new Date).getFullYear(),h=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();var l=Math.max(h,f);t()[a>>2]=
60*l;r()[b>>2]=Number(h!=f);b=m=>{var n=Math.abs(m);return`UTC${0<=m?"-":"+"}${String(Math.floor(n/60)).padStart(2,"0")}${String(n%60).padStart(2,"0")}`};a=b(h);b=b(f);f<h?(D(a,d,17),D(b,e,17)):(D(a,e,17),D(b,d,17))},emscripten_console_warn:a=>{console.warn(B(a))},emscripten_date_now:()=>Date.now(),emscripten_errn:(a,b)=>y(B(a,b)),emscripten_get_now:()=>performance.now(),emscripten_glBindFramebuffer:qb,emscripten_glClear:rb,emscripten_glClearColor:sb,emscripten_glClearStencil:tb,emscripten_glGetIntegerv:xb,
emscripten_glReadPixels:Ab,emscripten_resize_heap:a=>{var b=q().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-g.buffer.byteLength+65535)/65536|0;try{g.grow(e);p();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},emscripten_stack_snapshot:function(){var a=Error().stack.toString().split("\n");"Error"==a[0]&&a.shift();Cb(a);P.I=Bb();P.T=a;return P.I},emscripten_stack_unwind_buffer:(a,
b,d)=>{if(P.I==a)var e=P.T;else e=Error().stack.toString().split("\n"),"Error"==e[0]&&e.shift(),Cb(e);for(var f=3;e[f]&&Bb()!=a;)++f;for(a=0;a<d&&e[a+f];++a)r()[b+4*a>>2]=Bb();return a},emscripten_wasm_worker_post_function_v:(a,b)=>{C[a].postMessage({_wsc:b,x:[]})},emscripten_webgl_enable_extension:function(a,b){a=K[a];b=B(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&Za(E);"OES_vertex_array_object"==b&&$a(E);"WEBGL_draw_buffers"==b&&ab(E);"WEBGL_draw_instanced_base_vertex_base_instance"==
b&&bb(E);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&cb(E);"WEBGL_multi_draw"==b&&(E.U=E.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(E.P=E.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(E.O=E.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(E.Z=E.getExtension("WEBGL_polygon_mode"));return!!a.m.getExtension(b)},emscripten_webgl_make_context_current:a=>{O=K[a];w.aa=E=O?.m;return!a||E?0:-5},environ_get:(a,b)=>{var d=0;Fb().forEach((e,
f)=>{var h=b+d;f=t()[a+4*f>>2]=h;for(h=0;h<e.length;++h)c()[f++]=e.charCodeAt(h);c()[f]=0;d+=e.length+1});return 0},environ_sizes_get:(a,b)=>{var d=Fb();t()[a>>2]=d.length;var e=0;d.forEach(f=>e+=f.length+1);t()[b>>2]=e;return 0},fd_close:()=>52,fd_pread:function(){return 52},fd_read:()=>52,fd_seek:function(){return 70},fd_write:(a,b,d,e)=>{for(var f=0,h=0;h<d;h++){var l=t()[b>>2],m=t()[b+4>>2];b+=8;for(var n=0;n<m;n++){var u=q()[l+n],S=Gb[a];0===u||10===u?((1===a?pa:y)(Wa(S)),S.length=0):S.push(u)}f+=
m}t()[e>>2]=f;return 0},glActiveTexture:a=>E.activeTexture(a),glAttachShader:(a,b)=>{E.attachShader(G[a],J[b])},glBeginQueryEXT:(a,b)=>{E.o.beginQueryEXT(a,L[b])},glBindAttribLocation:(a,b,d)=>{E.bindAttribLocation(G[a],b,B(d))},glBindBuffer:(a,b)=>{35051==a?E.D=b:35052==a&&(E.v=b);E.bindBuffer(a,F[b])},glBindBufferRange:(a,b,d,e,f)=>{E.bindBufferRange(a,b,F[d],e,f)},glBindFramebuffer:qb,glBindRenderbuffer:(a,b)=>{E.bindRenderbuffer(a,H[b])},glBindTexture:(a,b)=>{E.bindTexture(a,I[b])},glBindVertexArray:a=>
{E.bindVertexArray(gb[a])},glBlendEquationSeparate:(a,b)=>E.blendEquationSeparate(a,b),glBlendFuncSeparate:(a,b,d,e)=>E.blendFuncSeparate(a,b,d,e),glBlitFramebuffer:(a,b,d,e,f,h,l,m,n,u)=>E.blitFramebuffer(a,b,d,e,f,h,l,m,n,u),glBufferData:(a,b,d,e)=>{2<=O.version?d&&b?E.bufferData(a,q(),e,d,b):E.bufferData(a,b,e):E.bufferData(a,d?q().subarray(d,d+b):b,e)},glBufferSubData:(a,b,d,e)=>{2<=O.version?d&&E.bufferSubData(a,b,q(),e,d):E.bufferSubData(a,b,q().subarray(e,e+d))},glCheckFramebufferStatus:a=>
E.checkFramebufferStatus(a),glClear:rb,glClearColor:sb,glClearDepthf:a=>E.clearDepth(a),glClearStencil:tb,glColorMask:(a,b,d,e)=>{E.colorMask(!!a,!!b,!!d,!!e)},glCompileShader:a=>{E.compileShader(J[a])},glCreateProgram:()=>{var a=M(G),b=E.createProgram();b.name=a;b.C=b.A=b.B=0;b.G=1;G[a]=b;return a},glCreateShader:a=>{var b=M(J);J[b]=E.createShader(a);return b},glCullFace:a=>E.cullFace(a),glDeleteBuffers:(a,b)=>{for(var d=0;d<a;d++){var e=r()[b+4*d>>2],f=F[e];f&&(E.deleteBuffer(f),f.name=0,F[e]=null,
e==E.D&&(E.D=0),e==E.v&&(E.v=0))}},glDeleteFramebuffers:(a,b)=>{for(var d=0;d<a;++d){var e=r()[b+4*d>>2],f=fb[e];f&&(E.deleteFramebuffer(f),f.name=0,fb[e]=null)}},glDeleteProgram:a=>{if(a){var b=G[a];b?(E.deleteProgram(b),b.name=0,G[a]=null):N||=1281}},glDeleteQueriesEXT:(a,b)=>{for(var d=0;d<a;d++){var e=r()[b+4*d>>2],f=L[e];f&&(E.o.deleteQueryEXT(f),L[e]=null)}},glDeleteRenderbuffers:(a,b)=>{for(var d=0;d<a;d++){var e=r()[b+4*d>>2],f=H[e];f&&(E.deleteRenderbuffer(f),f.name=0,H[e]=null)}},glDeleteShader:a=>
{if(a){var b=J[a];b?(E.deleteShader(b),J[a]=null):N||=1281}},glDeleteSync:a=>{if(a){var b=hb[a];b?(E.deleteSync(b),b.name=0,hb[a]=null):N||=1281}},glDeleteTextures:(a,b)=>{for(var d=0;d<a;d++){var e=r()[b+4*d>>2],f=I[e];f&&(E.deleteTexture(f),f.name=0,I[e]=null)}},glDeleteVertexArrays:(a,b)=>{for(var d=0;d<a;d++){var e=r()[b+4*d>>2];E.deleteVertexArray(gb[e]);gb[e]=null}},glDepthFunc:a=>E.depthFunc(a),glDepthMask:a=>{E.depthMask(!!a)},glDepthRangef:(a,b)=>E.depthRange(a,b),glDetachShader:(a,b)=>{E.detachShader(G[a],
J[b])},glDisable:a=>E.disable(a),glDisableVertexAttribArray:a=>{E.disableVertexAttribArray(a)},glDrawArrays:(a,b,d)=>{E.drawArrays(a,b,d)},glDrawElements:(a,b,d,e)=>{E.drawElements(a,b,d,e)},glEnable:a=>E.enable(a),glEnableVertexAttribArray:a=>{E.enableVertexAttribArray(a)},glEndQueryEXT:a=>{E.o.endQueryEXT(a)},glFenceSync:(a,b)=>(a=E.fenceSync(a,b))?(b=M(hb),a.name=b,hb[b]=a,b):0,glFinish:()=>E.finish(),glFlush:()=>E.flush(),glFramebufferRenderbuffer:(a,b,d,e)=>{E.framebufferRenderbuffer(a,b,d,H[e])},
glFramebufferTexture2D:(a,b,d,e,f)=>{E.framebufferTexture2D(a,b,d,I[e],f)},glFrontFace:a=>E.frontFace(a),glGenBuffers:(a,b)=>{mb(a,b,"createBuffer",F)},glGenFramebuffers:(a,b)=>{mb(a,b,"createFramebuffer",fb)},glGenQueriesEXT:(a,b)=>{for(var d=0;d<a;d++){var e=E.o.createQueryEXT();if(!e){for(N||=1282;d<a;)r()[b+4*d++>>2]=0;break}var f=M(L);e.name=f;L[f]=e;r()[b+4*d>>2]=f}},glGenRenderbuffers:(a,b)=>{mb(a,b,"createRenderbuffer",H)},glGenTextures:(a,b)=>{mb(a,b,"createTexture",I)},glGenVertexArrays:(a,
b)=>{mb(a,b,"createVertexArray",gb)},glGenerateMipmap:a=>E.generateMipmap(a),glGetActiveUniform:(a,b,d,e,f,h,l)=>{a=G[a];if(b=E.getActiveUniform(a,b))d=l&&D(b.name,l,d),e&&(r()[e>>2]=d),f&&(r()[f>>2]=b.size),h&&(r()[h>>2]=b.type)},glGetActiveUniformBlockName:(a,b,d,e,f)=>{a=G[a];if(a=E.getActiveUniformBlockName(a,b))f&&0<d?(d=D(a,f,d),e&&(r()[e>>2]=d)):e&&(r()[e>>2]=0)},glGetActiveUniformBlockiv:(a,b,d,e)=>{if(e)if(a=G[a],35393==d)d=E.getActiveUniformBlockName(a,b),r()[e>>2]=d.length+1;else{if(a=
E.getActiveUniformBlockParameter(a,b,d),null!==a)if(35395==d)for(d=0;d<a.length;d++)r()[e+4*d>>2]=a[d];else r()[e>>2]=a}else N||=1281},glGetBooleanv:(a,b)=>wb(a,b,4),glGetError:()=>{var a=E.getError()||N;N=0;return a},glGetFloatv:(a,b)=>wb(a,b,2),glGetFramebufferAttachmentParameteriv:(a,b,d,e)=>{a=E.getFramebufferAttachmentParameter(a,b,d);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r()[e>>2]=a},glGetIntegerv:xb,glGetProgramInfoLog:(a,b,d,e)=>{a=E.getProgramInfoLog(G[a]);
null===a&&(a="(unknown error)");b=0<b&&e?D(a,e,b):0;d&&(r()[d>>2]=b)},glGetProgramiv:(a,b,d)=>{if(d)if(a>=eb)N||=1281;else if(a=G[a],35716==b)a=E.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r()[d>>2]=a.length+1;else if(35719==b){if(!a.C){var e=E.getProgramParameter(a,35718);for(b=0;b<e;++b)a.C=Math.max(a.C,E.getActiveUniform(a,b).name.length+1)}r()[d>>2]=a.C}else if(35722==b){if(!a.A)for(e=E.getProgramParameter(a,35721),b=0;b<e;++b)a.A=Math.max(a.A,E.getActiveAttrib(a,b).name.length+1);r()[d>>
2]=a.A}else if(35381==b){if(!a.B)for(e=E.getProgramParameter(a,35382),b=0;b<e;++b)a.B=Math.max(a.B,E.getActiveUniformBlockName(a,b).length+1);r()[d>>2]=a.B}else r()[d>>2]=E.getProgramParameter(a,b);else N||=1281},glGetQueryObjectui64vEXT:(a,b,d)=>{if(d){a=L[a];b=2>O.version?E.o.getQueryObjectEXT(a,b):E.getQueryParameter(a,b);var e;"boolean"==typeof b?e=b?1:0:e=b;ub(d,e)}else N||=1281},glGetQueryObjectuivEXT:(a,b,d)=>{if(d){a=E.o.getQueryObjectEXT(L[a],b);var e;"boolean"==typeof a?e=a?1:0:e=a;r()[d>>
2]=e}else N||=1281},glGetShaderInfoLog:(a,b,d,e)=>{a=E.getShaderInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&e?D(a,e,b):0;d&&(r()[d>>2]=b)},glGetShaderSource:(a,b,d,e)=>{if(a=E.getShaderSource(J[a]))b=0<b&&e?D(a,e,b):0,d&&(r()[d>>2]=b)},glGetShaderiv:(a,b,d)=>{d?35716==b?(a=E.getShaderInfoLog(J[a]),null===a&&(a="(unknown error)"),a=a?a.length+1:0,r()[d>>2]=a):35720==b?(a=(a=E.getShaderSource(J[a]))?a.length+1:0,r()[d>>2]=a):r()[d>>2]=E.getShaderParameter(J[a],b):N||=1281},glGetString:a=>{var b=
ib[a];if(!b){switch(a){case 7939:b=Ib(vb().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=E.getParameter(a))||(N||=1280);b=b?Ib(b):0;break;case 7938:b=E.getParameter(7938);var d=`OpenGL ES 2.0 (${b})`;2<=O.version&&(d=`OpenGL ES 3.0 (${b})`);b=Ib(d);break;case 35724:b=E.getParameter(35724);d=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==d&&(3==d[1].length&&(d[1]+="0"),b=`OpenGL ES GLSL ES ${d[1]} (${b})`);b=Ib(b);break;default:N||=1280}ib[a]=b}return b},glGetStringi:(a,
b)=>{if(2>O.version)return N||=1282,0;var d=jb[a];if(d)return 0>b||b>=d.length?(N||=1281,0):d[b];switch(a){case 7939:return d=vb().map(Ib),d=jb[a]=d,0>b||b>=d.length?(N||=1281,0):d[b];default:return N||=1280,0}},glGetUniformBlockIndex:(a,b)=>E.getUniformBlockIndex(G[a],B(b)),glGetUniformLocation:(a,b)=>{b=B(b);if(a=G[a]){var d=a,e=d.u,f=d.L,h;if(!e){d.u=e={};d.K={};var l=E.getProgramParameter(d,35718);for(h=0;h<l;++h){var m=E.getActiveUniform(d,h);var n=m.name;m=m.size;var u=Jb(n);u=0<u?n.slice(0,
u):n;var S=d.G;d.G+=m;f[u]=[m,S];for(n=0;n<m;++n)e[S]=n,d.K[S++]=u}}d=a.u;e=0;f=b;h=Jb(b);0<h&&(e=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.L[f])&&e<f[0]&&(e+=f[1],d[e]=d[e]||E.getUniformLocation(a,b)))return e}else N||=1281;return-1},glInvalidateFramebuffer:(a,b,d)=>{for(var e=Kb[b],f=0;f<b;f++)e[f]=r()[d+4*f>>2];E.invalidateFramebuffer(a,e)},glIsBuffer:a=>(a=F[a])?E.isBuffer(a):0,glIsFramebuffer:a=>(a=fb[a])?E.isFramebuffer(a):0,glIsProgram:a=>(a=G[a])?E.isProgram(a):0,glIsRenderbuffer:a=>
(a=H[a])?E.isRenderbuffer(a):0,glIsShader:a=>(a=J[a])?E.isShader(a):0,glIsTexture:a=>(a=I[a])?E.isTexture(a):0,glLinkProgram:a=>{a=G[a];E.linkProgram(a);a.u=0;a.L={}},glPixelStorei:(a,b)=>{3317==a?kb=b:3314==a&&(lb=b);E.pixelStorei(a,b)},glReadPixels:Ab,glRenderbufferStorage:(a,b,d,e)=>E.renderbufferStorage(a,b,d,e),glRenderbufferStorageMultisample:(a,b,d,e,f)=>E.renderbufferStorageMultisample(a,b,d,e,f),glScissor:(a,b,d,e)=>E.scissor(a,b,d,e),glShaderBinary:()=>{N||=1280},glShaderSource:(a,b,d,e)=>
{for(var f="",h=0;h<b;++h){var l=e?t()[e+4*h>>2]:void 0;f+=B(t()[d+4*h>>2],l)}E.shaderSource(J[a],f)},glStencilFuncSeparate:(a,b,d,e)=>E.stencilFuncSeparate(a,b,d,e),glStencilMaskSeparate:(a,b)=>E.stencilMaskSeparate(a,b),glStencilOpSeparate:(a,b,d,e)=>E.stencilOpSeparate(a,b,d,e),glTexImage2D:(a,b,d,e,f,h,l,m,n)=>{if(2<=O.version){if(E.v){E.texImage2D(a,b,d,e,f,h,l,m,n);return}if(n){var u=yb(m);n>>>=31-Math.clz32(u.BYTES_PER_ELEMENT);E.texImage2D(a,b,d,e,f,h,l,m,u,n);return}}u=n?zb(m,l,e,f,n):null;
E.texImage2D(a,b,d,e,f,h,l,m,u)},glTexParameterfv:(a,b,d)=>{d=v()[d>>2];E.texParameterf(a,b,d)},glTexParameteri:(a,b,d)=>E.texParameteri(a,b,d),glTexSubImage2D:(a,b,d,e,f,h,l,m,n)=>{if(2<=O.version){if(E.v){E.texSubImage2D(a,b,d,e,f,h,l,m,n);return}if(n){var u=yb(m);E.texSubImage2D(a,b,d,e,f,h,l,m,u,n>>>31-Math.clz32(u.BYTES_PER_ELEMENT));return}}n=n?zb(m,l,f,h,n):null;E.texSubImage2D(a,b,d,e,f,h,l,m,n)},glUniform1fv:(a,b,d)=>{if(2<=O.version)b&&E.uniform1fv(Q(a),v(),d>>2,b);else{if(288>=b)for(var e=
R[b],f=0;f<b;++f)e[f]=v()[d+4*f>>2];else e=v().subarray(d>>2,d+4*b>>2);E.uniform1fv(Q(a),e)}},glUniform1i:(a,b)=>{E.uniform1i(Q(a),b)},glUniform2fv:(a,b,d)=>{if(2<=O.version)b&&E.uniform2fv(Q(a),v(),d>>2,2*b);else{if(144>=b){b*=2;for(var e=R[b],f=0;f<b;f+=2)e[f]=v()[d+4*f>>2],e[f+1]=v()[d+(4*f+4)>>2]}else e=v().subarray(d>>2,d+8*b>>2);E.uniform2fv(Q(a),e)}},glUniform3fv:(a,b,d)=>{if(2<=O.version)b&&E.uniform3fv(Q(a),v(),d>>2,3*b);else{if(96>=b){b*=3;for(var e=R[b],f=0;f<b;f+=3)e[f]=v()[d+4*f>>2],
e[f+1]=v()[d+(4*f+4)>>2],e[f+2]=v()[d+(4*f+8)>>2]}else e=v().subarray(d>>2,d+12*b>>2);E.uniform3fv(Q(a),e)}},glUniform4fv:(a,b,d)=>{if(2<=O.version)b&&E.uniform4fv(Q(a),v(),d>>2,4*b);else{if(72>=b){var e=R[4*b],f=v();d>>=2;b*=4;for(var h=0;h<b;h+=4){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3]}}else e=v().subarray(d>>2,d+16*b>>2);E.uniform4fv(Q(a),e)}},glUniformBlockBinding:(a,b,d)=>{a=G[a];E.uniformBlockBinding(a,b,d)},glUniformMatrix2fv:(a,b,d,e)=>{if(2<=O.version)b&&E.uniformMatrix2fv(Q(a),
!!d,v(),e>>2,4*b);else{if(72>=b){b*=4;for(var f=R[b],h=0;h<b;h+=4)f[h]=v()[e+4*h>>2],f[h+1]=v()[e+(4*h+4)>>2],f[h+2]=v()[e+(4*h+8)>>2],f[h+3]=v()[e+(4*h+12)>>2]}else f=v().subarray(e>>2,e+16*b>>2);E.uniformMatrix2fv(Q(a),!!d,f)}},glUniformMatrix3fv:(a,b,d,e)=>{if(2<=O.version)b&&E.uniformMatrix3fv(Q(a),!!d,v(),e>>2,9*b);else{if(32>=b){b*=9;for(var f=R[b],h=0;h<b;h+=9)f[h]=v()[e+4*h>>2],f[h+1]=v()[e+(4*h+4)>>2],f[h+2]=v()[e+(4*h+8)>>2],f[h+3]=v()[e+(4*h+12)>>2],f[h+4]=v()[e+(4*h+16)>>2],f[h+5]=v()[e+
(4*h+20)>>2],f[h+6]=v()[e+(4*h+24)>>2],f[h+7]=v()[e+(4*h+28)>>2],f[h+8]=v()[e+(4*h+32)>>2]}else f=v().subarray(e>>2,e+36*b>>2);E.uniformMatrix3fv(Q(a),!!d,f)}},glUniformMatrix4fv:(a,b,d,e)=>{if(2<=O.version)b&&E.uniformMatrix4fv(Q(a),!!d,v(),e>>2,16*b);else{if(18>=b){var f=R[16*b],h=v();e>>=2;b*=16;for(var l=0;l<b;l+=16){var m=e+l;f[l]=h[m];f[l+1]=h[m+1];f[l+2]=h[m+2];f[l+3]=h[m+3];f[l+4]=h[m+4];f[l+5]=h[m+5];f[l+6]=h[m+6];f[l+7]=h[m+7];f[l+8]=h[m+8];f[l+9]=h[m+9];f[l+10]=h[m+10];f[l+11]=h[m+11];
f[l+12]=h[m+12];f[l+13]=h[m+13];f[l+14]=h[m+14];f[l+15]=h[m+15]}}else f=v().subarray(e>>2,e+64*b>>2);E.uniformMatrix4fv(Q(a),!!d,f)}},glUseProgram:a=>{a=G[a];E.useProgram(a);E.N=a},glVertexAttribPointer:(a,b,d,e,f,h)=>{E.vertexAttribPointer(a,b,d,!!e,f,h)},glViewport:(a,b,d,e)=>E.viewport(a,b,d,e),glWaitSync:(a,b,d,e)=>{E.waitSync(hb[a],b,(d>>>0)+4294967296*e)},invoke_ii:Bc,invoke_iii:Cc,invoke_iiiii:Dc,invoke_iiiiiii:Ec,invoke_vi:Fc,invoke_vii:Gc,invoke_viii:Hc,invoke_viiiiiii:Ic,memory:g,proc_exit:Qa,
skwasm_captureImageBitmap:Lb,skwasm_connectThread:Ob,skwasm_createGlTextureFromTextureSource:Pb,skwasm_destroyContext:Qb,skwasm_dispatchDisposeSurface:Rb,skwasm_dispatchRasterizeImage:Sb,skwasm_dispatchRenderPictures:Tb,skwasm_dispatchResizeSurface:Ub,skwasm_dispatchTransferCanvas:Vb,skwasm_dispatchTriggerContextLoss:Wb,skwasm_disposeAssociatedObjectOnThread:Xb,skwasm_getAssociatedObject:Yb,skwasm_getGlContextForCanvas:Zb,skwasm_isSingleThreaded:$b,skwasm_postRasterizeResult:ac,skwasm_reportContextLossTriggered:bc,
skwasm_reportContextLost:cc,skwasm_reportInitialized:dc,skwasm_reportResizeComplete:ec,skwasm_resizeCanvas:fc,skwasm_resolveAndPostImages:gc,skwasm_setAssociatedObjectOnThread:hc,skwasm_triggerContextLossOnCanvas:ic},W=function(){function a(d,e){W=d.exports;w.wasmExports=W;A=W.__indirect_function_table;wa.unshift(W.__wasm_call_ctors);qa=e;z--;0==z&&(null!==Fa&&(clearInterval(Fa),Fa=null),Ga&&(d=Ga,Ga=null,d()));return W}var b={env:Jc,wasi_snapshot_preview1:Jc};z++;if(w.instantiateWasm)try{return w.instantiateWasm(b,
a)}catch(d){y(`Module.instantiateWasm callback failed with error: ${d}`),fa(d)}Ja??=Ia("wimp.wasm")?"wimp.wasm":ma("wimp.wasm");Ma(b,function(d){a(d.instance,d.module)}).catch(fa);return{}}();w._canvas_saveLayer=(a,b,d,e)=>(w._canvas_saveLayer=W.canvas_saveLayer)(a,b,d,e);w._canvas_save=a=>(w._canvas_save=W.canvas_save)(a);w._canvas_restore=a=>(w._canvas_restore=W.canvas_restore)(a);w._canvas_restoreToCount=(a,b)=>(w._canvas_restoreToCount=W.canvas_restoreToCount)(a,b);
w._canvas_getSaveCount=a=>(w._canvas_getSaveCount=W.canvas_getSaveCount)(a);w._canvas_translate=(a,b,d)=>(w._canvas_translate=W.canvas_translate)(a,b,d);w._canvas_scale=(a,b,d)=>(w._canvas_scale=W.canvas_scale)(a,b,d);w._canvas_rotate=(a,b)=>(w._canvas_rotate=W.canvas_rotate)(a,b);w._canvas_skew=(a,b,d)=>(w._canvas_skew=W.canvas_skew)(a,b,d);w._canvas_transform=(a,b)=>(w._canvas_transform=W.canvas_transform)(a,b);w._canvas_clear=(a,b)=>(w._canvas_clear=W.canvas_clear)(a,b);
w._canvas_clipRect=(a,b,d,e)=>(w._canvas_clipRect=W.canvas_clipRect)(a,b,d,e);w._canvas_clipRRect=(a,b,d)=>(w._canvas_clipRRect=W.canvas_clipRRect)(a,b,d);w._canvas_clipPath=(a,b,d)=>(w._canvas_clipPath=W.canvas_clipPath)(a,b,d);w._canvas_drawColor=(a,b,d)=>(w._canvas_drawColor=W.canvas_drawColor)(a,b,d);w._canvas_drawLine=(a,b,d,e,f,h)=>(w._canvas_drawLine=W.canvas_drawLine)(a,b,d,e,f,h);w._canvas_drawPaint=(a,b)=>(w._canvas_drawPaint=W.canvas_drawPaint)(a,b);
w._canvas_drawRect=(a,b,d)=>(w._canvas_drawRect=W.canvas_drawRect)(a,b,d);w._canvas_drawRRect=(a,b,d)=>(w._canvas_drawRRect=W.canvas_drawRRect)(a,b,d);w._canvas_drawDRRect=(a,b,d,e)=>(w._canvas_drawDRRect=W.canvas_drawDRRect)(a,b,d,e);w._canvas_drawOval=(a,b,d)=>(w._canvas_drawOval=W.canvas_drawOval)(a,b,d);w._canvas_drawCircle=(a,b,d,e,f)=>(w._canvas_drawCircle=W.canvas_drawCircle)(a,b,d,e,f);w._canvas_drawArc=(a,b,d,e,f,h)=>(w._canvas_drawArc=W.canvas_drawArc)(a,b,d,e,f,h);
w._canvas_drawPath=(a,b,d)=>(w._canvas_drawPath=W.canvas_drawPath)(a,b,d);w._canvas_drawShadow=(a,b,d,e,f,h)=>(w._canvas_drawShadow=W.canvas_drawShadow)(a,b,d,e,f,h);w._canvas_drawParagraph=(a,b,d,e)=>(w._canvas_drawParagraph=W.canvas_drawParagraph)(a,b,d,e);w._canvas_drawPicture=(a,b)=>(w._canvas_drawPicture=W.canvas_drawPicture)(a,b);w._canvas_drawImage=(a,b,d,e,f,h)=>(w._canvas_drawImage=W.canvas_drawImage)(a,b,d,e,f,h);
w._canvas_drawImageRect=(a,b,d,e,f,h)=>(w._canvas_drawImageRect=W.canvas_drawImageRect)(a,b,d,e,f,h);w._canvas_drawImageNine=(a,b,d,e,f,h)=>(w._canvas_drawImageNine=W.canvas_drawImageNine)(a,b,d,e,f,h);w._canvas_drawVertices=(a,b,d,e)=>(w._canvas_drawVertices=W.canvas_drawVertices)(a,b,d,e);w._canvas_drawPoints=(a,b,d,e,f)=>(w._canvas_drawPoints=W.canvas_drawPoints)(a,b,d,e,f);w._canvas_drawAtlas=(a,b,d,e,f,h,l,m,n)=>(w._canvas_drawAtlas=W.canvas_drawAtlas)(a,b,d,e,f,h,l,m,n);
w._canvas_getTransform=(a,b)=>(w._canvas_getTransform=W.canvas_getTransform)(a,b);w._canvas_getLocalClipBounds=(a,b)=>(w._canvas_getLocalClipBounds=W.canvas_getLocalClipBounds)(a,b);w._canvas_getDeviceClipBounds=(a,b)=>(w._canvas_getDeviceClipBounds=W.canvas_getDeviceClipBounds)(a,b);w._canvas_quickReject=(a,b)=>(w._canvas_quickReject=W.canvas_quickReject)(a,b);w._contourMeasureIter_create=(a,b,d)=>(w._contourMeasureIter_create=W.contourMeasureIter_create)(a,b,d);
w._contourMeasureIter_next=a=>(w._contourMeasureIter_next=W.contourMeasureIter_next)(a);w._contourMeasureIter_dispose=a=>(w._contourMeasureIter_dispose=W.contourMeasureIter_dispose)(a);w._contourMeasure_dispose=a=>(w._contourMeasure_dispose=W.contourMeasure_dispose)(a);w._contourMeasure_length=a=>(w._contourMeasure_length=W.contourMeasure_length)(a);w._contourMeasure_isClosed=a=>(w._contourMeasure_isClosed=W.contourMeasure_isClosed)(a);
w._contourMeasure_getPosTan=(a,b,d,e)=>(w._contourMeasure_getPosTan=W.contourMeasure_getPosTan)(a,b,d,e);w._contourMeasure_getSegment=(a,b,d,e)=>(w._contourMeasure_getSegment=W.contourMeasure_getSegment)(a,b,d,e);w._skData_create=a=>(w._skData_create=W.skData_create)(a);w._skData_getPointer=a=>(w._skData_getPointer=W.skData_getPointer)(a);w._skData_getConstPointer=a=>(w._skData_getConstPointer=W.skData_getConstPointer)(a);w._skData_getSize=a=>(w._skData_getSize=W.skData_getSize)(a);
w._skData_dispose=a=>(w._skData_dispose=W.skData_dispose)(a);w._imageFilter_createBlur=(a,b,d)=>(w._imageFilter_createBlur=W.imageFilter_createBlur)(a,b,d);w._imageFilter_createDilate=(a,b)=>(w._imageFilter_createDilate=W.imageFilter_createDilate)(a,b);w._imageFilter_createErode=(a,b)=>(w._imageFilter_createErode=W.imageFilter_createErode)(a,b);w._imageFilter_createMatrix=(a,b)=>(w._imageFilter_createMatrix=W.imageFilter_createMatrix)(a,b);
w._imageFilter_createFromColorFilter=a=>(w._imageFilter_createFromColorFilter=W.imageFilter_createFromColorFilter)(a);w._imageFilter_compose=(a,b)=>(w._imageFilter_compose=W.imageFilter_compose)(a,b);w._imageFilter_dispose=a=>(w._imageFilter_dispose=W.imageFilter_dispose)(a);w._imageFilter_getFilterBounds=(a,b)=>(w._imageFilter_getFilterBounds=W.imageFilter_getFilterBounds)(a,b);w._colorFilter_createMode=(a,b)=>(w._colorFilter_createMode=W.colorFilter_createMode)(a,b);
w._colorFilter_createMatrix=a=>(w._colorFilter_createMatrix=W.colorFilter_createMatrix)(a);w._colorFilter_createSRGBToLinearGamma=()=>(w._colorFilter_createSRGBToLinearGamma=W.colorFilter_createSRGBToLinearGamma)();w._colorFilter_createLinearToSRGBGamma=()=>(w._colorFilter_createLinearToSRGBGamma=W.colorFilter_createLinearToSRGBGamma)();w._colorFilter_dispose=a=>(w._colorFilter_dispose=W.colorFilter_dispose)(a);w._maskFilter_createBlur=(a,b)=>(w._maskFilter_createBlur=W.maskFilter_createBlur)(a,b);
w._maskFilter_dispose=a=>(w._maskFilter_dispose=W.maskFilter_dispose)(a);w._fontCollection_create=()=>(w._fontCollection_create=W.fontCollection_create)();w._fontCollection_dispose=a=>(w._fontCollection_dispose=W.fontCollection_dispose)(a);w._typeface_create=a=>(w._typeface_create=W.typeface_create)(a);w._typeface_dispose=a=>(w._typeface_dispose=W.typeface_dispose)(a);w._typefaces_filterCoveredCodePoints=(a,b,d,e)=>(w._typefaces_filterCoveredCodePoints=W.typefaces_filterCoveredCodePoints)(a,b,d,e);
w._fontCollection_registerTypeface=(a,b,d)=>(w._fontCollection_registerTypeface=W.fontCollection_registerTypeface)(a,b,d);w._fontCollection_clearCaches=a=>(w._fontCollection_clearCaches=W.fontCollection_clearCaches)(a);w._image_createFromPicture=(a,b,d)=>(w._image_createFromPicture=W.image_createFromPicture)(a,b,d);w._image_createFromPixels=(a,b,d,e,f)=>(w._image_createFromPixels=W.image_createFromPixels)(a,b,d,e,f);
w._image_createFromTextureSource=(a,b,d,e)=>(w._image_createFromTextureSource=W.image_createFromTextureSource)(a,b,d,e);w._image_ref=a=>(w._image_ref=W.image_ref)(a);w._image_dispose=a=>(w._image_dispose=W.image_dispose)(a);w._image_getWidth=a=>(w._image_getWidth=W.image_getWidth)(a);w._image_getHeight=a=>(w._image_getHeight=W.image_getHeight)(a);w._skwasm_getLiveObjectCounts=a=>(w._skwasm_getLiveObjectCounts=W.skwasm_getLiveObjectCounts)(a);
w._paint_create=(a,b,d,e,f,h,l,m,n)=>(w._paint_create=W.paint_create)(a,b,d,e,f,h,l,m,n);w._paint_dispose=a=>(w._paint_dispose=W.paint_dispose)(a);w._paint_setShader=(a,b)=>(w._paint_setShader=W.paint_setShader)(a,b);w._paint_setImageFilter=(a,b)=>(w._paint_setImageFilter=W.paint_setImageFilter)(a,b);w._paint_setColorFilter=(a,b)=>(w._paint_setColorFilter=W.paint_setColorFilter)(a,b);w._paint_setMaskFilter=(a,b)=>(w._paint_setMaskFilter=W.paint_setMaskFilter)(a,b);
w._path_create=()=>(w._path_create=W.path_create)();w._path_dispose=a=>(w._path_dispose=W.path_dispose)(a);w._path_copy=a=>(w._path_copy=W.path_copy)(a);w._path_setFillType=(a,b)=>(w._path_setFillType=W.path_setFillType)(a,b);w._path_getFillType=a=>(w._path_getFillType=W.path_getFillType)(a);w._path_moveTo=(a,b,d)=>(w._path_moveTo=W.path_moveTo)(a,b,d);w._path_relativeMoveTo=(a,b,d)=>(w._path_relativeMoveTo=W.path_relativeMoveTo)(a,b,d);w._path_lineTo=(a,b,d)=>(w._path_lineTo=W.path_lineTo)(a,b,d);
w._path_relativeLineTo=(a,b,d)=>(w._path_relativeLineTo=W.path_relativeLineTo)(a,b,d);w._path_quadraticBezierTo=(a,b,d,e,f)=>(w._path_quadraticBezierTo=W.path_quadraticBezierTo)(a,b,d,e,f);w._path_relativeQuadraticBezierTo=(a,b,d,e,f)=>(w._path_relativeQuadraticBezierTo=W.path_relativeQuadraticBezierTo)(a,b,d,e,f);w._path_cubicTo=(a,b,d,e,f,h,l)=>(w._path_cubicTo=W.path_cubicTo)(a,b,d,e,f,h,l);w._path_relativeCubicTo=(a,b,d,e,f,h,l)=>(w._path_relativeCubicTo=W.path_relativeCubicTo)(a,b,d,e,f,h,l);
w._path_conicTo=(a,b,d,e,f,h)=>(w._path_conicTo=W.path_conicTo)(a,b,d,e,f,h);w._path_relativeConicTo=(a,b,d,e,f,h)=>(w._path_relativeConicTo=W.path_relativeConicTo)(a,b,d,e,f,h);w._path_arcToOval=(a,b,d,e,f)=>(w._path_arcToOval=W.path_arcToOval)(a,b,d,e,f);w._path_arcToRotated=(a,b,d,e,f,h,l,m)=>(w._path_arcToRotated=W.path_arcToRotated)(a,b,d,e,f,h,l,m);w._path_relativeArcToRotated=(a,b,d,e,f,h,l,m)=>(w._path_relativeArcToRotated=W.path_relativeArcToRotated)(a,b,d,e,f,h,l,m);
w._path_addRect=(a,b)=>(w._path_addRect=W.path_addRect)(a,b);w._path_addOval=(a,b)=>(w._path_addOval=W.path_addOval)(a,b);w._path_addArc=(a,b,d,e)=>(w._path_addArc=W.path_addArc)(a,b,d,e);w._path_addPolygon=(a,b,d,e)=>(w._path_addPolygon=W.path_addPolygon)(a,b,d,e);w._path_addRRect=(a,b)=>(w._path_addRRect=W.path_addRRect)(a,b);w._path_addPath=(a,b,d,e)=>(w._path_addPath=W.path_addPath)(a,b,d,e);w._path_close=a=>(w._path_close=W.path_close)(a);w._path_reset=a=>(w._path_reset=W.path_reset)(a);
w._path_contains=(a,b,d)=>(w._path_contains=W.path_contains)(a,b,d);w._path_transform=(a,b)=>(w._path_transform=W.path_transform)(a,b);w._path_getBounds=(a,b)=>(w._path_getBounds=W.path_getBounds)(a,b);w._path_combine=(a,b,d)=>(w._path_combine=W.path_combine)(a,b,d);w._path_getSvgString=a=>(w._path_getSvgString=W.path_getSvgString)(a);w._pictureRecorder_create=()=>(w._pictureRecorder_create=W.pictureRecorder_create)();w._pictureRecorder_dispose=a=>(w._pictureRecorder_dispose=W.pictureRecorder_dispose)(a);
w._pictureRecorder_beginRecording=(a,b)=>(w._pictureRecorder_beginRecording=W.pictureRecorder_beginRecording)(a,b);w._pictureRecorder_endRecording=a=>(w._pictureRecorder_endRecording=W.pictureRecorder_endRecording)(a);w._picture_getCullRect=(a,b)=>(w._picture_getCullRect=W.picture_getCullRect)(a,b);w._picture_ref=a=>(w._picture_ref=W.picture_ref)(a);w._picture_dispose=a=>(w._picture_dispose=W.picture_dispose)(a);w._picture_approximateBytesUsed=a=>(w._picture_approximateBytesUsed=W.picture_approximateBytesUsed)(a);
w._shader_createLinearGradient=(a,b,d,e,f,h)=>(w._shader_createLinearGradient=W.shader_createLinearGradient)(a,b,d,e,f,h);w._shader_createRadialGradient=(a,b,d,e,f,h,l,m)=>(w._shader_createRadialGradient=W.shader_createRadialGradient)(a,b,d,e,f,h,l,m);w._shader_createConicalGradient=(a,b,d,e,f,h,l,m)=>(w._shader_createConicalGradient=W.shader_createConicalGradient)(a,b,d,e,f,h,l,m);
w._shader_createSweepGradient=(a,b,d,e,f,h,l,m,n)=>(w._shader_createSweepGradient=W.shader_createSweepGradient)(a,b,d,e,f,h,l,m,n);w._shader_dispose=a=>(w._shader_dispose=W.shader_dispose)(a);w._runtimeEffect_create=a=>(w._runtimeEffect_create=W.runtimeEffect_create)(a);w._runtimeEffect_dispose=a=>(w._runtimeEffect_dispose=W.runtimeEffect_dispose)(a);w._runtimeEffect_getUniformSize=a=>(w._runtimeEffect_getUniformSize=W.runtimeEffect_getUniformSize)(a);
w._shader_createRuntimeEffectShader=(a,b,d,e)=>(w._shader_createRuntimeEffectShader=W.shader_createRuntimeEffectShader)(a,b,d,e);w._shader_createFromImage=(a,b,d,e,f)=>(w._shader_createFromImage=W.shader_createFromImage)(a,b,d,e,f);w._uniformData_create=a=>(w._uniformData_create=W.uniformData_create)(a);w._uniformData_dispose=a=>(w._uniformData_dispose=W.uniformData_dispose)(a);w._uniformData_getPointer=a=>(w._uniformData_getPointer=W.uniformData_getPointer)(a);
w._skString_allocate=a=>(w._skString_allocate=W.skString_allocate)(a);w._skString_getData=a=>(w._skString_getData=W.skString_getData)(a);w._skString_getLength=a=>(w._skString_getLength=W.skString_getLength)(a);w._skString_free=a=>(w._skString_free=W.skString_free)(a);w._skString16_allocate=a=>(w._skString16_allocate=W.skString16_allocate)(a);w._skString16_getData=a=>(w._skString16_getData=W.skString16_getData)(a);w._skString16_free=a=>(w._skString16_free=W.skString16_free)(a);
w._skwasm_isWimp=()=>(w._skwasm_isWimp=W.skwasm_isWimp)();w._surface_create=()=>(w._surface_create=W.surface_create)();w._surface_setCanvas=(a,b)=>(w._surface_setCanvas=W.surface_setCanvas)(a,b);var nc=w._surface_receiveCanvasOnWorker=(a,b,d)=>(nc=w._surface_receiveCanvasOnWorker=W.surface_receiveCanvasOnWorker)(a,b,d),oc=w._surface_onInitialized=(a,b)=>(oc=w._surface_onInitialized=W.surface_onInitialized)(a,b);w._surface_setSize=(a,b,d)=>(w._surface_setSize=W.surface_setSize)(a,b,d);
var pc=w._surface_resizeOnWorker=(a,b,d,e)=>(pc=w._surface_resizeOnWorker=W.surface_resizeOnWorker)(a,b,d,e),qc=w._surface_onResizeComplete=(a,b)=>(qc=w._surface_onResizeComplete=W.surface_onResizeComplete)(a,b);w._surface_getThreadId=a=>(w._surface_getThreadId=W.surface_getThreadId)(a);w._surface_getGlContext=a=>(w._surface_getGlContext=W.surface_getGlContext)(a);w._surface_triggerContextLoss=a=>(w._surface_triggerContextLoss=W.surface_triggerContextLoss)(a);
var rc=w._surface_triggerContextLossOnWorker=(a,b)=>(rc=w._surface_triggerContextLossOnWorker=W.surface_triggerContextLossOnWorker)(a,b),sc=w._surface_onContextLossTriggered=(a,b)=>(sc=w._surface_onContextLossTriggered=W.surface_onContextLossTriggered)(a,b),tc=w._surface_reportContextLost=(a,b)=>(tc=w._surface_reportContextLost=W.surface_reportContextLost)(a,b);w._surface_setCallbackHandler=(a,b)=>(w._surface_setCallbackHandler=W.surface_setCallbackHandler)(a,b);
w._surface_destroy=a=>(w._surface_destroy=W.surface_destroy)(a);var wc=w._surface_dispose=a=>(wc=w._surface_dispose=W.surface_dispose)(a);w._surface_setResourceCacheLimitBytes=(a,b)=>(w._surface_setResourceCacheLimitBytes=W.surface_setResourceCacheLimitBytes)(a,b);w._surface_renderPictures=(a,b,d)=>(w._surface_renderPictures=W.surface_renderPictures)(a,b,d);var uc=w._surface_renderPicturesOnWorker=(a,b,d,e,f)=>(uc=w._surface_renderPicturesOnWorker=W.surface_renderPicturesOnWorker)(a,b,d,e,f);
w._surface_rasterizeImage=(a,b,d)=>(w._surface_rasterizeImage=W.surface_rasterizeImage)(a,b,d);
var xc=w._surface_rasterizeImageOnWorker=(a,b,d,e)=>(xc=w._surface_rasterizeImageOnWorker=W.surface_rasterizeImageOnWorker)(a,b,d,e),vc=w._surface_onRenderComplete=(a,b,d)=>(vc=w._surface_onRenderComplete=W.surface_onRenderComplete)(a,b,d),yc=w._surface_onRasterizeComplete=(a,b,d)=>(yc=w._surface_onRasterizeComplete=W.surface_onRasterizeComplete)(a,b,d),zc=w._surface_onContextLost=a=>(zc=w._surface_onContextLost=W.surface_onContextLost)(a);
w._skwasm_isMultiThreaded=()=>(w._skwasm_isMultiThreaded=W.skwasm_isMultiThreaded)();w._lineMetrics_create=(a,b,d,e,f,h,l,m,n)=>(w._lineMetrics_create=W.lineMetrics_create)(a,b,d,e,f,h,l,m,n);w._lineMetrics_dispose=a=>(w._lineMetrics_dispose=W.lineMetrics_dispose)(a);w._lineMetrics_getHardBreak=a=>(w._lineMetrics_getHardBreak=W.lineMetrics_getHardBreak)(a);w._lineMetrics_getAscent=a=>(w._lineMetrics_getAscent=W.lineMetrics_getAscent)(a);w._lineMetrics_getDescent=a=>(w._lineMetrics_getDescent=W.lineMetrics_getDescent)(a);
w._lineMetrics_getUnscaledAscent=a=>(w._lineMetrics_getUnscaledAscent=W.lineMetrics_getUnscaledAscent)(a);w._lineMetrics_getHeight=a=>(w._lineMetrics_getHeight=W.lineMetrics_getHeight)(a);w._lineMetrics_getWidth=a=>(w._lineMetrics_getWidth=W.lineMetrics_getWidth)(a);w._lineMetrics_getLeft=a=>(w._lineMetrics_getLeft=W.lineMetrics_getLeft)(a);w._lineMetrics_getBaseline=a=>(w._lineMetrics_getBaseline=W.lineMetrics_getBaseline)(a);w._lineMetrics_getLineNumber=a=>(w._lineMetrics_getLineNumber=W.lineMetrics_getLineNumber)(a);
w._lineMetrics_getStartIndex=a=>(w._lineMetrics_getStartIndex=W.lineMetrics_getStartIndex)(a);w._lineMetrics_getEndIndex=a=>(w._lineMetrics_getEndIndex=W.lineMetrics_getEndIndex)(a);w._paragraph_dispose=a=>(w._paragraph_dispose=W.paragraph_dispose)(a);w._paragraph_getWidth=a=>(w._paragraph_getWidth=W.paragraph_getWidth)(a);w._paragraph_getHeight=a=>(w._paragraph_getHeight=W.paragraph_getHeight)(a);w._paragraph_getLongestLine=a=>(w._paragraph_getLongestLine=W.paragraph_getLongestLine)(a);
w._paragraph_getMinIntrinsicWidth=a=>(w._paragraph_getMinIntrinsicWidth=W.paragraph_getMinIntrinsicWidth)(a);w._paragraph_getMaxIntrinsicWidth=a=>(w._paragraph_getMaxIntrinsicWidth=W.paragraph_getMaxIntrinsicWidth)(a);w._paragraph_getAlphabeticBaseline=a=>(w._paragraph_getAlphabeticBaseline=W.paragraph_getAlphabeticBaseline)(a);w._paragraph_getIdeographicBaseline=a=>(w._paragraph_getIdeographicBaseline=W.paragraph_getIdeographicBaseline)(a);
w._paragraph_getDidExceedMaxLines=a=>(w._paragraph_getDidExceedMaxLines=W.paragraph_getDidExceedMaxLines)(a);w._paragraph_layout=(a,b)=>(w._paragraph_layout=W.paragraph_layout)(a,b);w._paragraph_getPositionForOffset=(a,b,d,e)=>(w._paragraph_getPositionForOffset=W.paragraph_getPositionForOffset)(a,b,d,e);w._paragraph_getClosestGlyphInfoAtCoordinate=(a,b,d,e,f,h)=>(w._paragraph_getClosestGlyphInfoAtCoordinate=W.paragraph_getClosestGlyphInfoAtCoordinate)(a,b,d,e,f,h);
w._paragraph_getGlyphInfoAt=(a,b,d,e,f)=>(w._paragraph_getGlyphInfoAt=W.paragraph_getGlyphInfoAt)(a,b,d,e,f);w._paragraph_getWordBoundary=(a,b,d)=>(w._paragraph_getWordBoundary=W.paragraph_getWordBoundary)(a,b,d);w._paragraph_getLineCount=a=>(w._paragraph_getLineCount=W.paragraph_getLineCount)(a);w._paragraph_getLineNumberAt=(a,b)=>(w._paragraph_getLineNumberAt=W.paragraph_getLineNumberAt)(a,b);
w._paragraph_getLineMetricsAtIndex=(a,b)=>(w._paragraph_getLineMetricsAtIndex=W.paragraph_getLineMetricsAtIndex)(a,b);w._textBoxList_dispose=a=>(w._textBoxList_dispose=W.textBoxList_dispose)(a);w._textBoxList_getLength=a=>(w._textBoxList_getLength=W.textBoxList_getLength)(a);w._textBoxList_getBoxAtIndex=(a,b,d)=>(w._textBoxList_getBoxAtIndex=W.textBoxList_getBoxAtIndex)(a,b,d);w._paragraph_getBoxesForRange=(a,b,d,e,f)=>(w._paragraph_getBoxesForRange=W.paragraph_getBoxesForRange)(a,b,d,e,f);
w._paragraph_getBoxesForPlaceholders=a=>(w._paragraph_getBoxesForPlaceholders=W.paragraph_getBoxesForPlaceholders)(a);w._paragraph_getUnresolvedCodePoints=(a,b,d)=>(w._paragraph_getUnresolvedCodePoints=W.paragraph_getUnresolvedCodePoints)(a,b,d);w._paragraphBuilder_dispose=a=>(w._paragraphBuilder_dispose=W.paragraphBuilder_dispose)(a);w._paragraphBuilder_addPlaceholder=(a,b,d,e,f,h)=>(w._paragraphBuilder_addPlaceholder=W.paragraphBuilder_addPlaceholder)(a,b,d,e,f,h);
w._paragraphBuilder_addText=(a,b)=>(w._paragraphBuilder_addText=W.paragraphBuilder_addText)(a,b);w._paragraphBuilder_getUtf8Text=(a,b)=>(w._paragraphBuilder_getUtf8Text=W.paragraphBuilder_getUtf8Text)(a,b);w._paragraphBuilder_pushStyle=(a,b)=>(w._paragraphBuilder_pushStyle=W.paragraphBuilder_pushStyle)(a,b);w._paragraphBuilder_pop=a=>(w._paragraphBuilder_pop=W.paragraphBuilder_pop)(a);w._unicodePositionBuffer_create=a=>(w._unicodePositionBuffer_create=W.unicodePositionBuffer_create)(a);
w._unicodePositionBuffer_getDataPointer=a=>(w._unicodePositionBuffer_getDataPointer=W.unicodePositionBuffer_getDataPointer)(a);w._unicodePositionBuffer_free=a=>(w._unicodePositionBuffer_free=W.unicodePositionBuffer_free)(a);w._lineBreakBuffer_create=a=>(w._lineBreakBuffer_create=W.lineBreakBuffer_create)(a);w._lineBreakBuffer_getDataPointer=a=>(w._lineBreakBuffer_getDataPointer=W.lineBreakBuffer_getDataPointer)(a);w._lineBreakBuffer_free=a=>(w._lineBreakBuffer_free=W.lineBreakBuffer_free)(a);
w._paragraphStyle_create=()=>(w._paragraphStyle_create=W.paragraphStyle_create)();w._paragraphStyle_dispose=a=>(w._paragraphStyle_dispose=W.paragraphStyle_dispose)(a);w._paragraphStyle_setTextAlign=(a,b)=>(w._paragraphStyle_setTextAlign=W.paragraphStyle_setTextAlign)(a,b);w._paragraphStyle_setTextDirection=(a,b)=>(w._paragraphStyle_setTextDirection=W.paragraphStyle_setTextDirection)(a,b);w._paragraphStyle_setMaxLines=(a,b)=>(w._paragraphStyle_setMaxLines=W.paragraphStyle_setMaxLines)(a,b);
w._paragraphStyle_setHeight=(a,b)=>(w._paragraphStyle_setHeight=W.paragraphStyle_setHeight)(a,b);w._paragraphStyle_setTextHeightBehavior=(a,b,d)=>(w._paragraphStyle_setTextHeightBehavior=W.paragraphStyle_setTextHeightBehavior)(a,b,d);w._paragraphStyle_setEllipsis=(a,b)=>(w._paragraphStyle_setEllipsis=W.paragraphStyle_setEllipsis)(a,b);w._paragraphStyle_setStrutStyle=(a,b)=>(w._paragraphStyle_setStrutStyle=W.paragraphStyle_setStrutStyle)(a,b);
w._paragraphStyle_setTextStyle=(a,b)=>(w._paragraphStyle_setTextStyle=W.paragraphStyle_setTextStyle)(a,b);w._paragraphStyle_setApplyRoundingHack=(a,b)=>(w._paragraphStyle_setApplyRoundingHack=W.paragraphStyle_setApplyRoundingHack)(a,b);w._strutStyle_create=()=>(w._strutStyle_create=W.strutStyle_create)();w._strutStyle_dispose=a=>(w._strutStyle_dispose=W.strutStyle_dispose)(a);w._strutStyle_setFontFamilies=(a,b,d)=>(w._strutStyle_setFontFamilies=W.strutStyle_setFontFamilies)(a,b,d);
w._strutStyle_setFontSize=(a,b)=>(w._strutStyle_setFontSize=W.strutStyle_setFontSize)(a,b);w._strutStyle_setHeight=(a,b)=>(w._strutStyle_setHeight=W.strutStyle_setHeight)(a,b);w._strutStyle_setHalfLeading=(a,b)=>(w._strutStyle_setHalfLeading=W.strutStyle_setHalfLeading)(a,b);w._strutStyle_setLeading=(a,b)=>(w._strutStyle_setLeading=W.strutStyle_setLeading)(a,b);w._strutStyle_setFontStyle=(a,b,d)=>(w._strutStyle_setFontStyle=W.strutStyle_setFontStyle)(a,b,d);
w._strutStyle_setForceStrutHeight=(a,b)=>(w._strutStyle_setForceStrutHeight=W.strutStyle_setForceStrutHeight)(a,b);w._textStyle_create=()=>(w._textStyle_create=W.textStyle_create)();w._textStyle_copy=a=>(w._textStyle_copy=W.textStyle_copy)(a);w._textStyle_dispose=a=>(w._textStyle_dispose=W.textStyle_dispose)(a);w._textStyle_setColor=(a,b)=>(w._textStyle_setColor=W.textStyle_setColor)(a,b);w._textStyle_setDecoration=(a,b)=>(w._textStyle_setDecoration=W.textStyle_setDecoration)(a,b);
w._textStyle_setDecorationColor=(a,b)=>(w._textStyle_setDecorationColor=W.textStyle_setDecorationColor)(a,b);w._textStyle_setDecorationStyle=(a,b)=>(w._textStyle_setDecorationStyle=W.textStyle_setDecorationStyle)(a,b);w._textStyle_setDecorationThickness=(a,b)=>(w._textStyle_setDecorationThickness=W.textStyle_setDecorationThickness)(a,b);w._textStyle_setFontStyle=(a,b,d)=>(w._textStyle_setFontStyle=W.textStyle_setFontStyle)(a,b,d);
w._textStyle_setTextBaseline=(a,b)=>(w._textStyle_setTextBaseline=W.textStyle_setTextBaseline)(a,b);w._textStyle_clearFontFamilies=a=>(w._textStyle_clearFontFamilies=W.textStyle_clearFontFamilies)(a);w._textStyle_addFontFamilies=(a,b,d)=>(w._textStyle_addFontFamilies=W.textStyle_addFontFamilies)(a,b,d);w._textStyle_setFontSize=(a,b)=>(w._textStyle_setFontSize=W.textStyle_setFontSize)(a,b);w._textStyle_setLetterSpacing=(a,b)=>(w._textStyle_setLetterSpacing=W.textStyle_setLetterSpacing)(a,b);
w._textStyle_setWordSpacing=(a,b)=>(w._textStyle_setWordSpacing=W.textStyle_setWordSpacing)(a,b);w._textStyle_setHeight=(a,b)=>(w._textStyle_setHeight=W.textStyle_setHeight)(a,b);w._textStyle_setHalfLeading=(a,b)=>(w._textStyle_setHalfLeading=W.textStyle_setHalfLeading)(a,b);w._textStyle_setLocale=(a,b)=>(w._textStyle_setLocale=W.textStyle_setLocale)(a,b);w._textStyle_setBackground=(a,b)=>(w._textStyle_setBackground=W.textStyle_setBackground)(a,b);
w._textStyle_setForeground=(a,b)=>(w._textStyle_setForeground=W.textStyle_setForeground)(a,b);w._textStyle_addShadow=(a,b,d,e,f)=>(w._textStyle_addShadow=W.textStyle_addShadow)(a,b,d,e,f);w._textStyle_addFontFeature=(a,b,d)=>(w._textStyle_addFontFeature=W.textStyle_addFontFeature)(a,b,d);w._textStyle_setFontVariations=(a,b,d,e)=>(w._textStyle_setFontVariations=W.textStyle_setFontVariations)(a,b,d,e);w._vertices_create=(a,b,d,e,f,h,l)=>(w._vertices_create=W.vertices_create)(a,b,d,e,f,h,l);
w._vertices_dispose=a=>(w._vertices_dispose=W.vertices_dispose)(a);w._animatedImage_create=(a,b,d)=>(w._animatedImage_create=W.animatedImage_create)(a,b,d);w._animatedImage_dispose=a=>(w._animatedImage_dispose=W.animatedImage_dispose)(a);w._animatedImage_getFrameCount=a=>(w._animatedImage_getFrameCount=W.animatedImage_getFrameCount)(a);w._animatedImage_getRepetitionCount=a=>(w._animatedImage_getRepetitionCount=W.animatedImage_getRepetitionCount)(a);
w._animatedImage_getCurrentFrameDurationMilliseconds=a=>(w._animatedImage_getCurrentFrameDurationMilliseconds=W.animatedImage_getCurrentFrameDurationMilliseconds)(a);w._animatedImage_decodeNextFrame=a=>(w._animatedImage_decodeNextFrame=W.animatedImage_decodeNextFrame)(a);w._animatedImage_getCurrentFrame=a=>(w._animatedImage_getCurrentFrame=W.animatedImage_getCurrentFrame)(a);w._skwasm_isHeavy=()=>(w._skwasm_isHeavy=W.skwasm_isHeavy)();
w._paragraphBuilder_create=(a,b)=>(w._paragraphBuilder_create=W.paragraphBuilder_create)(a,b);w._paragraphBuilder_build=a=>(w._paragraphBuilder_build=W.paragraphBuilder_build)(a);w._paragraphBuilder_setGraphemeBreaksUtf16=(a,b)=>(w._paragraphBuilder_setGraphemeBreaksUtf16=W.paragraphBuilder_setGraphemeBreaksUtf16)(a,b);w._paragraphBuilder_setWordBreaksUtf16=(a,b)=>(w._paragraphBuilder_setWordBreaksUtf16=W.paragraphBuilder_setWordBreaksUtf16)(a,b);
w._paragraphBuilder_setLineBreaksUtf16=(a,b)=>(w._paragraphBuilder_setLineBreaksUtf16=W.paragraphBuilder_setLineBreaksUtf16)(a,b);w._dummyAPICalls=()=>(w._dummyAPICalls=W.dummyAPICalls)();var Hb=a=>(Hb=W.malloc)(a),Ac=(a,b)=>(Ac=W._emscripten_timeout)(a,b),X=(a,b)=>(X=W.setThrew)(a,b),Y=a=>(Y=W._emscripten_stack_restore)(a),kc=a=>(kc=W._emscripten_stack_alloc)(a),Z=()=>(Z=W.emscripten_stack_get_current)(),Aa=(a,b)=>(Aa=W._emscripten_wasm_worker_initialize)(a,b);
function Cc(a,b,d){var e=Z();try{return A.get(a)(b,d)}catch(f){Y(e);if(f!==f+0)throw f;X(1,0)}}function Gc(a,b,d){var e=Z();try{A.get(a)(b,d)}catch(f){Y(e);if(f!==f+0)throw f;X(1,0)}}function Bc(a,b){var d=Z();try{return A.get(a)(b)}catch(e){Y(d);if(e!==e+0)throw e;X(1,0)}}function Hc(a,b,d,e){var f=Z();try{A.get(a)(b,d,e)}catch(h){Y(f);if(h!==h+0)throw h;X(1,0)}}function Dc(a,b,d,e,f){var h=Z();try{return A.get(a)(b,d,e,f)}catch(l){Y(h);if(l!==l+0)throw l;X(1,0)}}
function Ic(a,b,d,e,f,h,l,m){var n=Z();try{A.get(a)(b,d,e,f,h,l,m)}catch(u){Y(n);if(u!==u+0)throw u;X(1,0)}}function Fc(a,b){var d=Z();try{A.get(a)(b)}catch(e){Y(d);if(e!==e+0)throw e;X(1,0)}}function Ec(a,b,d,e,f,h,l){var m=Z();try{return A.get(a)(b,d,e,f,h,l)}catch(n){Y(m);if(n!==n+0)throw n;X(1,0)}}w.wasmMemory=g;w.wasmExports=W;w.stackAlloc=lc;
w.addFunction=(a,b)=>{if(!U){U=new WeakMap;var d=A.length;if(U)for(var e=0;e<0+d;e++){var f=A.get(e);f&&U.set(f,e)}}if(d=U.get(a)||0)return d;if(jc.length)d=jc.pop();else{try{A.grow(1)}catch(m){if(!(m instanceof RangeError))throw m;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}d=A.length-1}try{A.set(d,a)}catch(m){if(!(m instanceof TypeError))throw m;if("function"==typeof WebAssembly.Function){e=WebAssembly.Function;f={i:"i32",j:"i64",f:"f32",d:"f64",e:"externref",p:"i32"};for(var h={parameters:[],
results:"v"==b[0]?[]:[f[b[0]]]},l=1;l<b.length;++l)h.parameters.push(f[b[l]]);b=new e(h,a)}else{e=[1];f=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124,e:111};e.push(96);l=b.length;128>l?e.push(l):e.push(l%128|128,l>>7);for(l=0;l<b.length;++l)e.push(h[b[l]]);"v"==f?e.push(0):e.push(1,h[f]);b=[0,97,115,109,1,0,0,0,1];f=e.length;128>f?b.push(f):b.push(f%128|128,f>>7);b.push(...e);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,
{e:{f:a}})).exports.f}A.set(d,b)}U.set(a,d);return d};var Kc,Lc;Ga=function Mc(){Kc||Nc();Kc||(Ga=Mc)};function Nc(){if(!(0<z))if(ka)ea(w),ya();else{if(!Lc&&(Lc=1,Ea(va),0<z))return;Kc||(Kc=1,w.calledRun=1,ra||(ya(),ea(w),Ea(xa)))}}Nc();moduleRtn=ha;


  return moduleRtn;
}
);
})();
export default wimp;
