name: flame_riverpod_example
resolution: workspace
description: Showcasing the flame_riverpod functionality.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.12.0 <4.0.0"
dependencies:
  flame: ^2.0.0-dev.0
  flame_riverpod: ^5.5.6-dev.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  material_ui: ^1.0.0

dev_dependencies:
  cupertino_ui: any
  flame_lint: ^1.4.4-dev.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
