name: flame_gamepads
resolution: workspace
description: Flame bindings to work with gamepads package
version: 0.0.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_gamepads
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - gamepads

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flame: ^1.36.0
  flutter:
    sdk: flutter
  gamepads: ^0.1.10

dev_dependencies:
  dartdoc: ^9.0.0
  flame_lint: ^1.4.3
  flutter_test:
    sdk: flutter
  gamepads_platform_interface: any
  test: any
